import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen overflow-hidden">
        <main className="flex-grow">
          {children}
        </main>
<div className="relative z-30 mt-[300px] flex">
  <img
    src="/rainbow_head.png"
    alt="Rainbow Footer Banner"
    className="relative mt-[300px] w-35 object-contain block shrink-0"
    style={{ bottom: '-49px' }}
  />  
  <img
    src="/rainbow_body.png"
    alt="Rainbow Footer Banner"
    className="relative w-71 object-contain block shrink-0"
    style={{ bottom: '-240px' }}
  />
    <img
    src="/rainbow_body.png"
    alt="Rainbow Footer Banner"
    className="relative w-71 object-contain block shrink-0"
    style={{ bottom: '-240px' }}
  />
    <img
    src="/rainbow_body.png"
    alt="Rainbow Footer Banner"
    className="relative w-71 object-contain block shrink-0"
    style={{ bottom: '-240px' }}
  />
    <img
    src="/rainbow_body.png"
    alt="Rainbow Footer Banner"
    className="relative w-71 object-contain block shrink-0"
    style={{ bottom: '-240px' }}
  />
    <img
    src="/rainbow_body.png"
    alt="Rainbow Footer Banner"
    className="relative w-71 object-contain block shrink-0"
    style={{ bottom: '-240px' }}
  />
    <img
    src="/rainbow_body.png"
    alt="Rainbow Footer Banner"
    className="relative w-71 object-contain block shrink-0"
    style={{ bottom: '-240px' }}
  />
    <img
    src="/rainbow_body.png"
    alt="Rainbow Footer Banner"
    className="relative w-71 object-contain block shrink-0"
    style={{ bottom: '-240px' }}
  />
    <img
    src="/rainbow_body.png"
    alt="Rainbow Footer Banner"
    className="relative w-71 object-contain block shrink-0"
    style={{ bottom: '-251px' }}
  />
    <img
    src="/rainbow_body.png"
    alt="Rainbow Footer Banner"
    className="relative w-71 object-contain block shrink-0"
    style={{ bottom: '-251px' }}
  />
</div>

<footer className="bg-purple-200 text-purple-800 text-center p-8 pt-15 relative z-0">
  <div className="w-full max-w-3xl mx-auto text-left mb-2">
    <h4 className="font-bold">CONTACT US</h4>
  </div>

  <div className="grid font-bold grid-cols-3 justify-items-center gap-y-1 w-full max-w-3xl mx-auto">
    <div>Phone</div>
    <div>Email</div>
    <div>Socials</div>
    <div>8493248</div>
    <div>jfewofmn@gmail.com</div>
    <div>@rainbow</div>
  </div>
</footer>

      </body>
    </html>
  );
}
